# Dependencies
markdown:         kramdown
highlighter:      rouge

# Setup
title:            Data Science
tagline:          'Blog by dchandra'
description:      'Blog by'
info:             '<br>Dinesh Chandrasekaran<br><font size="3">M.Sc., France, ASQ-CSSBB, <br> PMP, PMI-ACP,<br> SAFe® 4 Agilist (SA),<br> SAFe® 4 Practitioner (SP)<br></font>'
url:              https://dchandra1985.github.io
baseurl:          # the optional subpath of your site, e.g. "/blog"
                  # NB: This applies to all pages in your Jekyll site.
                  # If you want to move just the blog index pages but keep
                  # other pages at root, see the paginate_path and
                  # sidebar_blog_link below.


author:           
  name:           'Dinesh Chandrasekaran'
  url:
  flair:          'Share your knowledge.It’s a way to achieve immortality(Dalai Lama)'

paginate:         5
# paginate_path:    '/page:num'
                    # Or '/blog/page:num' if you want to move your index pages

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  
  




# Sidebar link settings
sidebar_home_link:  true
# sidebar_blog_link:  '/blog'   # By default, your home page is your blog
                                # page. If you change your paginate_path,
                                # set this to the root of the paginate_path
                                # to enable a separate blog link.

disqus:
  shortname:      dinesh-chandra

google_analytics: UA-126196456-1

# Used for Hydeout's own Github page. Feel free to remove for your
# own fork.
hydeout:
  version:          4.0.0
  github:             https://github.com/dchandra1985/Data_Science
  linkedin:           https://www.linkedin.com/in/dinesh-chandrasekaran-49731b15/
  
  
  
  

